fnum=int(input("Enter first number : "))
snum=int(input("Enter second number : "))
print("Addition: " , fnum+snum)
print("Subtraction: " , fnum-snum)
print("Multiplication: " , fnum*snum)
print("Division: " , fnum/snum)